### ISSUE TITLE
메인페이지 API 구현

### ISSUE THREAD

**Issue by kitaee** [O-M-N-M/OMNM-BackEnd#28]
- [x] 추천 룸메이트 9명 보여주기 (GET) -> 프사, 이름,나이, mbti,설문항목 일치 갯수(ex - 성향 일치율(퍼센트) ex. 75.5%(소수점 )) <예빈>
 - [x] 선택된 사용자 세부 프로필 (GET) -> 프사, 이름,나이, mbti,설문항목 일치 갯수(ex - 성향 일치율(퍼센트) ex.75.5%(소수점)),흡연여부, 학과, 생활패턴 , 수면 패턴, 청소 빈도, 국적, 군복무(여성일 경우 해당 항목 제외), 입실정보) <기태>
 - [x] 매칭 API 로그인 상태 임의 코드 제거 및 로그인 유지 코드 삽입
 
### 로그인 유지 !!

**Comment by kitaee** [comment]
일치율을 어떻게 저장할지? 아니면 API 호출할 때마다 계산할지? 토의 필요

**Comment by SL313** [comment]
전부 구현 완료 ~!
